### ISSUE TITLE
Improve overlay/interaction schema

### ISSUE THREAD

**Issue by Jason-Ku** [calpoly-csai/virtual-tour-concept#11]
Right now we have overlays and overlay types - instead, we can more clearly represent the relationship between overlays and the actions they perform when clicked with overlays and "interactions".

An overlay should have an array of interactions, each of which has its on jsx component.

(At least, that's what we're thinking?)

EX:
```
"overlays": [
          {
            "overlay_id": 1,
            "overlay_type": "SHOWINFO",
            "title": "What is this?",
            "description": "Truck info overlay",
            "position": [9, 5, 3],
            "args": {
              "information": "Your mom. Just kidding, it's a truck."
            }
          },
```

into:

```
"overlays": [
          {
            "overlay_id": 1,
            "title": "What is this?",
            "description": "Truck info overlay",
            "position": [9, 5, 3],
            "interactions": [
              {
                "interaction_type": SHOWINFO,
                "information": "pingu truck"
              }
            ]
          },
```

**Comment by richagadgil** [comment]
It might not be the best idea to have multiple types of interaction for one overlay. I think each overlay should have one type.

**Comment by Jason-Ku** [comment]
Thats what I thought to but there are allegedly overlays that will need to have multiple interactions (?). Would like another input from @Waidhoferj

**Comment by Waidhoferj** [comment]
It's totally open for discussion. My thought is that it would make sense to have modals with several actions rendered as tags at the bottom of the card. This gives us some flexibility since we can just stack buttons and make the card scrollable.
<img width="266" alt="Screen Shot 2021-03-03 at 8 42 56 AM" src="https://user-images.githubusercontent.com/33008436/109839953-76cc2f00-7bfc-11eb-98ad-ca93b978d32f.png">

**Comment by Jason-Ku** [comment]
Ah yes, that's what I pictured but did not have a great example for. I would personally prefer that overlays like these be able to have both interactions rather than have multiple overlays (not just as a dev but also as a user)

**Comment by thegooman** [comment]
Just saw this, looks great! Going to get started on it
